name: Continuous Integration

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

concurrency:
  # Cancel previous runs that are not completed yet
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  validate:
    runs-on: ubuntu-latest
    name: Validate
    steps:
      - name: Checkout credo-ethr-module
        uses: actions/checkout@v4

      - name: Setup NodeJS
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'yarn'

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Linting
        run: yarn lint

      - name: Prettier
        run: yarn check-format

      - name: Check Types
        run: yarn check-types

      - name: Compile
        run: yarn build
